version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: crossmite
      POSTGRES_PASSWORD: 1975
      POSTGRES_DB: Parking
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  station_service:
    container_name: freeSpace_service
    build: ./freeSpace_service/
    ports:
      - "8000:80"
    depends_on:
      - db

  ticket_service:
    restart: on-failure
    container_name: parking_service
    build: ./parking_service/
    ports:
      - "8001:80"
    depends_on:
      - db